### ISSUE TITLE
Not writing bytes correctly?

### ISSUE THREAD

**Issue by Chream** [rpav/fast-io#13]
I am having some trouble with the with-fast-output macro. Here is a test code:
```
(defun test (list)
  "doc"
  (fast-io:with-fast-output (out)
    (fast-io:fast-write-byte (fast-io:octets-from list) out)))
```
result:

CL-USER> (util-array::test (list 1))
#(191)
CL-USER> (util-array::test (list 1))
#(239)
CL-USER> (util-array::test (list 1))
#(191)
CL-USER> (util-array::test (list 1))
#(135)

Am I missing something here? Does not seem 100% random either. Is it reading some flags before the number? I can confirm that octets-from works.

**Comment by rpav** [comment]
This is because `fast-write-byte` is declared `(safety 0)`, which possibly shouldn't be the case, and it expects an *octet*, not an octet-vector.  What you probably want is `FAST-WRITE-SEQUENCE`, or if you really want to write single byte, `WRITE8` or `WRITEU8`, which check their input.

**Comment by Chream** [comment]
Thanks! yes I figured it out just now. If I remove (from-octets ...) In the actual code it works. I was just parsing single integers, hence the single byte read.
